# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ecommerceassessment:
    image: ecommerceassessment
    container_name: ecommerceassessment_api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
        - DOTNET_USE_POLLING_FILE_WATCHER=1
        - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=db,1433;Database=ecommerceassessment;User Id=sa;Password=qwertY12@3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
      - 5001
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    environment:
        SA_PASSWORD: "qwertY12@3"
        ACCEPT_EULA: "Y"
    ports: 
        - "1433:1433"
    volumes:
        - sql_data_volume:/var/opt/mssql
volumes: 
    sql_data_volume: